/**
 * Created by mac002 on 7/31/17.
 */
const SET_SESSION = 'SET_SESSION';
const SET_SESSION_DB_INFO = 'SET_SESSION_DB_INFO';
const SET_SESSION_REST_SERVER = 'SET_SESSION_REST_SERVER';
const SET_SESSION_LANGUAGE_CODE = 'SET_SESSION_LANGUAGE_CODE';
const SET_SESSION_USER_LOGIN = 'SET_SESSION_USER_LOGIN';
const SET_SESSION_USER_LOGOUT = 'SET_SESSION_USER_LOGOUT';
const SET_SESSION_UI_SCHEMAS = 'SET_SESSION_UI_SCHEMAS';
const SET_SESSION_DROPDOWNS = 'SET_SESSION_DROPDOWNS';

export default {
  SET_SESSION
  , SET_SESSION_DB_INFO
  , SET_SESSION_DROPDOWNS
  , SET_SESSION_LANGUAGE_CODE
  , SET_SESSION_REST_SERVER
  , SET_SESSION_UI_SCHEMAS
  , SET_SESSION_USER_LOGIN
  , SET_SESSION_USER_LOGOUT
};