/**
 * Created by mac002 on 7/31/17.
 */
const DB_SET_INFO = 'DB_SET_INFO';
const LANGUAGE_SET_CODE = 'LANGUAGE_SET_CODE';
const SET_DROPDOWNS = 'SET_DROPDOWNS';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

export default {
  DB_SET_INFO
  , LANGUAGE_SET_CODE
  , SET_DROPDOWNS
  , USER_LOGIN
  , USER_LOGOUT
};